//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ms_Profiles
    {
        public string ProfileID { get; set; }
        public string UserID { get; set; }
        public string Name { get; set; }
        public string NIK { get; set; }
        public string NIK_Photo { get; set; }
        public string No_Rekening { get; set; }
        public string Nama_Rekening { get; set; }
        public string Bank { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<bool> Verified { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.DateTime> LoginTime { get; set; }
    
        public virtual Ms_Users Ms_Users { get; set; }
    }
}
